"use strict";
/* ====================== data ====================== */
const SEASONS=[{n:'春',ic:'🌸'},{n:'夏',ic:'☀️'},{n:'秋',ic:'🍂'},{n:'冬',ic:'❄️'}];
const RAR=[
  {n:'普通',c:'#a8a094',s:1},
  {n:'少见',c:'#5da863',s:2},
  {n:'稀有',c:'#4090d6',s:3},
  {n:'珍稀',c:'#a06cd8',s:4},
  {n:'传说',c:'#d9a02a',s:5},
];
const EDI={
  edible:{t:'可食用',c:'#2e7d32',b:'#ddefd8'},
  careful:{t:'慎食',c:'#9a6a10',b:'#f4e8c8'},
  inedible:{t:'不宜食',c:'#6b5b40',b:'#ece4d0'},
  poison:{t:'有毒',c:'#b03030',b:'#f4dcd6'},
  deadly:{t:'剧毒',c:'#8a1420',b:'#f0ccc8'},
  med:{t:'药用',c:'#7a4fa0',b:'#e9def4'},
};
/* E2.2 解锁门槛重排（按 100 种收集体量的规划值，E3 内容上线前先按当前 40 种手感验证不卡关） */
const BIOMES={
  forest:{n:'阔叶林',ic:'🌳',req:0,desc:'栎树与桦树的领地，枯木上藏着惊喜'},
  meadow:{n:'草甸',ic:'🌾',req:0,desc:'开阔草地，雨后会冒出蘑菇圈'},
  pine:{n:'松针林',ic:'🌲',req:6,desc:'松脂香里埋着秋日的珍宝'},
  wetland:{n:'溪谷湿地',ic:'💧',req:14,desc:'潮湿幽暗，美丽与危险并存'},
  bamboo:{n:'竹林幽径',ic:'🎋',req:22,desc:'翠竹疏影，湿润清幽，竹叶终年不落'},
  grove:{n:'灵境秘林',ic:'✨',req:32,desc:'暮色永驻的魔法林地'},
  alpine:{n:'高山苔甸',ic:'🏔',req:44,desc:'苔草覆石，碎雪不化，珍稀之物藏在最冷处'},
};
const SUBTXT={ground:'林地腐殖土',wood:'倒木、朽木上',stump:'树桩及其周围',trunk:'活树树干基部',grass:'草地、草丛间',ring:'开阔草地（常成蘑菇圈）',buried:'埋于地下，需循迹寻掘'};
const HOSTTXT={oak:'栎树（橡树）',birch:'桦树',pine:'松树',willow:'柳树',bamboo:'竹'};

/* art keys: shape,h,w,cap,cap2,gill,stemC,sw,stemH, ring,volva,
   warts/wartC, scales/scaleC, zones, fib, slime, pits, specks/speckC,
   rainbow, glow, cluster, layers, inky, alpha, umbo */
const SP=[
/* ---------- 阔叶林 forest ---------- */
{id:'shiitake',n:'香菇',en:'Lentinula edodes',biome:'forest',seasons:[0,2],r:0,edi:'edible',sub:'wood',host:'oak',rain:false,
 lore:'褐伞龟裂如绽开的花纹，香气沉厚。山民在春秋两季的枯栎木上寻它，冬日里最暖的一锅汤。',
 art:{shape:'convex',h:26,w:28,cap:'#7a5230',cap2:'#9a7248',gill:'#e8dab8',stemC:'#d8c8a2',sw:.22,scales:true,scaleC:'#e8d9b8'}},
{id:'oyster',n:'平菇',en:'Pleurotus ostreatus',biome:'forest',seasons:[0,2,3],r:0,edi:'edible',sub:'wood',host:null,rain:false,
 lore:'层叠如灰色的贝壳，攀在倒木上一簇簇地长。天越冷它越精神，是冬林里少有的收获。',
 art:{shape:'shelf',h:24,w:34,cap:'#b3aa99',cap2:'#8f8878',gill:'#ece4d2',layers:3}},
{id:'woodear',n:'木耳',en:'Auricularia auricula',biome:'forest',seasons:[0,1,2],r:0,edi:'edible',sub:'wood',host:null,rain:true,
 lore:'胶质柔韧，一场透雨之后，从腐木里舒展成一只只深褐的小耳朵，晒干了能存一整年。',
 art:{shape:'ear',h:22,w:28,cap:'#4d3226',cap2:'#6b4634',slime:true}},
{id:'enoki',n:'金针菇',en:'Flammulina velutipes',biome:'forest',seasons:[2,3],r:1,edi:'edible',sub:'stump',host:null,rain:false,
 lore:'野生的金针菇是琥珀色的，顶着雪从树桩缝里挤出来，故又名"冬菇"。菌柄下端有一层深色绒毛。',
 art:{shape:'convex',h:22,w:12,cap:'#d9973c',cap2:'#eab85e',gill:'#f0e6c8',stemC:'#e2d3a8',sw:.16,slime:true,cluster:5}},
{id:'chant',n:'鸡油菌',en:'Cantharellus cibarius',biome:'forest',seasons:[1,2],r:1,edi:'edible',sub:'ground',host:'oak',rain:false,
 lore:'金黄的小喇叭，杏子般的清香。它与栎树根共生，只肯在老林子的树荫下现身。',
 art:{shape:'funnel',h:24,w:26,cap:'#e2a622',cap2:'#c9891a',stemC:'#e7c45f',sw:.3}},
{id:'porcini',n:'美味牛肝菌',en:'Boletus edulis',biome:'forest',seasons:[1,2],r:2,edi:'edible',sub:'ground',host:'oak',rain:false,
 lore:'圆顶肥厚如烤面包，菌柄粗壮带网纹。盛夏雷雨后钻出栎树下，是欧洲人与云南人共同的心头好。',
 art:{shape:'convex',h:34,w:36,cap:'#7e4f2a',cap2:'#a06a3a',gill:'#d8cf9a',stemC:'#e3d5ac',sw:.42,fib:true}},
{id:'amanita',n:'毒蝇伞',en:'Amanita muscaria',biome:'forest',seasons:[2],r:2,edi:'poison',sub:'ground',host:'birch',rain:false,
 lore:'红伞白点，童话插画里的常客。它与桦树共生，秋天成群出现在桦树脚下，美得让人忘了它有毒。',
 art:{shape:'convex',h:30,w:32,cap:'#c93222',cap2:'#e05538',gill:'#f2ecda',stemC:'#f0e8d4',sw:.26,ring:true,volva:true,warts:9,wartC:'#f6efe0'}},
{id:'reishi',n:'灵芝',en:'Ganoderma lingzhi',biome:'forest',seasons:[1,2],r:3,edi:'med',sub:'trunk',host:'oak',rain:false,
 lore:'漆光环纹，红褐镶金边。古人称之仙草，悬生在老栎树干上，像谁遗落的一方云肩。',
 art:{shape:'shelf',h:24,w:34,cap:'#8a2c16',cap2:'#c96a28',gill:'#e8ddb8',layers:1,zones:true,slime:true,rimC:'#e8c96a'}},
{id:'truffle',n:'黑松露',en:'Tuber melanosporum',biome:'forest',seasons:[3],r:4,edi:'edible',sub:'buried',host:'oak',rain:false,
 lore:'藏于栎树根下的黑色钻石，寒冬正是成熟时。地表只留一点隆起与幽香，唯有耐心的人能掘得。',
 art:{shape:'truffle',h:18,w:22,cap:'#38291d',cap2:'#57402c'}},
{id:'jizong',n:'鸡枞',en:'Termitomyces',biome:'forest',seasons:[1],r:3,edi:'edible',sub:'ground',host:null,rain:true,
 lore:'与白蚁共生的奇菌，长长的假根直通蚁巢。三伏天一场雨后破土，鲜甜赛过鸡汤，故名鸡枞。',
 art:{shape:'umbo',h:36,w:26,cap:'#8a7a5e',cap2:'#b0a284',gill:'#efe8d4',stemC:'#e8e0ca',sw:.2,fib:true,umboC:'#5f5340'}},
{id:'trumpet',n:'黑喇叭菌',en:'Craterellus cornucopioides',biome:'forest',seasons:[2],r:2,edi:'edible',sub:'ground',host:'oak',rain:false,
 lore:'墨黑的小号角藏在落叶间，几乎隐形。法国人叫它"死亡号角"，却也叫它"穷人的松露"。',
 art:{shape:'trumpet',h:26,w:22,cap:'#423a33',cap2:'#5d5348',stemC:'#332c26'}},
/* ---------- 阔叶林 forest 新增（E3 批A） ---------- */
{id:'caesar',n:'橙盖鹅膏',en:'Amanita caesarea',biome:'forest',seasons:[1,2],r:1,edi:'edible',sub:'ground',host:'oak',rain:false,
 lore:'橙红华盖立在栎树荫下，柄基裹着雪白菌托，菌褶却是难得的金黄色。古罗马人奉之为"凯撒的餐桌"，鹅膏家族里少有的珍馐。',
 art:{shape:'convex',h:30,w:30,cap:'#e8821e',cap2:'#f4a83a',gill:'#f4d896',stemC:'#f0d472',sw:.26,ring:true,volva:true}},
{id:'panther',n:'豹斑鹅膏',en:'Amanita pantherina',biome:'forest',seasons:[1,2],r:1,edi:'poison',sub:'ground',host:'birch',rain:false,
 lore:'灰褐伞面缀着细密白疣，像豹身的斑纹。常与橙盖鹅膏混生在桦树下，外形相近，毒性却截然不同——认错一次便追悔莫及。',
 art:{shape:'convex',h:28,w:30,cap:'#7a6248',cap2:'#93795a',gill:'#f0e8d4',stemC:'#eee6d2',sw:.24,ring:true,volva:true,warts:7,wartC:'#f6efe0'}},
{id:'maitake',n:'灰树花',en:'Grifola frondosa',biome:'forest',seasons:[2],r:1,edi:'edible',sub:'trunk',host:'oak',rain:true,
 lore:'层层叠叠如展开的羽扇，簇生在老栎树根部。日本人唤它舞茸，据说采得一丛能让人乐得手舞足蹈，故此得名。',
 art:{shape:'shelf',h:26,w:30,cap:'#6b5a3e',cap2:'#8a7550',gill:'#e8dcc0',layers:2,cluster:3}},
{id:'hericium',n:'猴头菇',en:'Hericium erinaceus',biome:'forest',seasons:[1,2],r:2,edi:'edible',sub:'trunk',host:'oak',rain:false,
 lore:'雪白绒球悬在栎树伤口处，细刺如猴首垂毛，故名猴头。质地似肉，炖汤软糯，是山珍席上难得的荤素两相宜。',
 art:{shape:'spine',h:30,w:30,cap:'#f2ecda',cap2:'#e0d8c0',gill:'#f7f3e6'}},
{id:'turkeytail',n:'云芝',en:'Trametes versicolor',biome:'forest',seasons:[0,1,2,3],r:0,edi:'inedible',sub:'wood',host:null,rain:false,
 lore:'薄薄的扇形一圈圈叠生在朽木上，环纹深浅相间如孔雀开屏，又似云雾层叠，故名云芝。四季常见却不宜下箸，多入药茶。',
 art:{shape:'shelf',h:14,w:20,cap:'#6a5a44',cap2:'#c8bda0',gill:'#d8cfb8',layers:1,concentric:true,bandC:['#3a4d52','#c9bd9c','#8a5a34','#e8e0cc','#4a6b6a','#7a4a2c'],rimC:'#f2ecd8'}},
{id:'artistconk',n:'树舌灵芝',en:'Ganoderma applanatum',biome:'forest',seasons:[0,1,2,3],r:1,edi:'med',sub:'trunk',host:null,rain:false,
 lore:'灰褐色的厚壳嵌在老树干上，经年不落，切开断面细腻如象牙。旧时画师爱在其背面孔层上刻字作画，故有"画家的孔菌"之称。',
 art:{shape:'shelf',h:30,w:38,cap:'#6f6252',cap2:'#8a7d68',gill:'#d8cfb8',layers:1,zones:true}},
{id:'redbelt',n:'红缘拟层孔菌',en:'Fomitopsis pinicola',biome:'forest',seasons:[0,1,2,3],r:1,edi:'inedible',sub:'trunk',host:null,rain:false,
 lore:'灰白的马蹄形壳边缘镶着一圈鲜艳的橘红，像谁给朽木系了根丝带。终年不谢，却木质坚硬不堪食用。',
 art:{shape:'shelf',h:22,w:30,cap:'#a89a82',cap2:'#c2b89a',gill:'#e8e0c8',layers:2,zones:true,rimC:'#c9432a'}},
{id:'chaga',n:'桦褐孔菌',en:'Inonotus obliquus',biome:'forest',seasons:[0,1,2,3],r:2,edi:'med',sub:'trunk',host:'birch',rain:false,
 lore:'黑褐的瘤块龟裂如烧焦的炭，紧贴桦树皮生长，内里却是温润的锈红色。西伯利亚人拿它煮茶驱寒，视若珍宝。',
 art:{shape:'ball',h:26,w:24,cap:'#231d18',cap2:'#3a2f26',warts:true,slime:true}},
{id:'mica',n:'晶粒鬼伞',en:'Coprinellus micaceus',biome:'forest',seasons:[0,1,2],r:0,edi:'inedible',sub:'stump',host:null,rain:true,
 lore:'褐黄小伞挤在树桩四周，伞面沾着细密的云母状颗粒，晨光下闪闪发亮，日头一晒颗粒便簌簌落尽。',
 art:{shape:'bell',h:20,w:14,cap:'#c9a06a',cap2:'#dcb87c',gill:'#8a7458',stemC:'#e6dcc0',sw:.16,specks:10,speckC:'#f4e8c0',cluster:5,fib:true}},
/* ---------- 草甸 meadow ---------- */
{id:'button',n:'双孢蘑菇',en:'Agaricus bisporus',biome:'meadow',seasons:[0,2],r:0,edi:'edible',sub:'grass',host:null,rain:false,
 lore:'白胖圆头，菌褶粉褐。世界上栽培最广的蘑菇，野生的它更喜欢肥沃的草地与春秋的凉意。',
 art:{shape:'convex',h:22,w:24,cap:'#ece4d0',cap2:'#d9cbae',gill:'#c49a84',stemC:'#efe6d2',sw:.3,ring:true}},
{id:'field',n:'四孢蘑菇',en:'Agaricus campestris',biome:'meadow',seasons:[1,2],r:0,edi:'edible',sub:'ring',host:null,rain:true,
 lore:'晨露未干时成圈冒出，一夜之间围出一个"仙女环"。传说那是精灵夜里跳舞踏出的脚印。',
 art:{shape:'convex',h:23,w:25,cap:'#e6dcc6',cap2:'#d0c2a2',gill:'#b98a74',stemC:'#e9e0cd',sw:.26,ring:true}},
{id:'straw',n:'草菇',en:'Volvariella volvacea',biome:'meadow',seasons:[1],r:0,edi:'edible',sub:'grass',host:null,rain:true,
 lore:'蛋形的灰褐小伞从草堆里钻出，基部裹着一层菌托。喜高温高湿，是南方三伏天的鲜味。',
 art:{shape:'bell',h:26,w:22,cap:'#77685a',cap2:'#94836f',gill:'#e8d8c2',stemC:'#dccfb4',sw:.24,volva:true}},
{id:'inky',n:'墨汁鬼伞',en:'Coprinopsis atramentaria',biome:'meadow',seasons:[0,1,2],r:0,edi:'careful',sub:'grass',host:null,rain:true,
 lore:'钟形灰帽带细密条纹，老去时整个伞缘化作墨汁滴落。趁它年轻时可食，但万万不可配酒。',
 art:{shape:'bell',h:26,w:20,cap:'#a29a8c',cap2:'#c2baa8',gill:'#8a8274',stemC:'#e6e0d2',sw:.2,fib:true,inky:true}},
{id:'puff',n:'马勃',en:'Lycoperdon perlatum',biome:'meadow',seasons:[1,2],r:0,edi:'edible',sub:'grass',host:null,rain:false,
 lore:'雪白的小圆球缀着细刺突，幼时切开如豆腐。熟透后轻轻一捏，便"噗"地喷出一团孢子烟。',
 art:{shape:'puff',h:18,w:18,cap:'#e8e0ca',cap2:'#cfc4a6',specks:14,speckC:'#b9ac8c'}},
{id:'gpuff',n:'巨型马勃',en:'Calvatia gigantea',biome:'meadow',seasons:[1,2],r:2,edi:'edible',sub:'grass',host:null,rain:false,
 lore:'草甸上滚出的白色巨球，大者赛过西瓜。远看像羊群里走失的一只，走近才知是菌中巨人。',
 art:{shape:'puff',h:30,w:34,cap:'#f2ecda',cap2:'#dcd2b6'}},
{id:'parasol',n:'高大环柄菇',en:'Macrolepiota procera',biome:'meadow',seasons:[1,2],r:1,edi:'edible',sub:'grass',host:null,rain:false,
 lore:'亭亭玉立过膝高，伞盖布满褐鳞，菌柄有蛇皮纹，菌环还能上下滑动，是草地上最优雅的身影。',
 art:{shape:'umbo',h:40,w:36,cap:'#cdb894',cap2:'#e0d0b0',gill:'#efe8d4',stemC:'#d4c09a',sw:.14,ring:true,scales:true,scaleC:'#6f5636',umboC:'#6f5636'}},
{id:'blewit',n:'紫丁香蘑',en:'Lepista nuda',biome:'meadow',seasons:[2,3],r:2,edi:'edible',sub:'grass',host:null,rain:false,
 lore:'通体淡紫如丁香，深秋霜降后才登场，能一直站到初雪。寒风里那一点紫，格外温柔。',
 art:{shape:'convex',h:24,w:27,cap:'#9b7fb8',cap2:'#b89ed0',gill:'#b0a0c8',stemC:'#a890c0',sw:.3}},
/* ---------- 草甸 meadow 新增（E3 批A） ---------- */
{id:'phallus',n:'白鬼笔',en:'Phallus impudicus',biome:'meadow',seasons:[1],r:1,edi:'careful',sub:'grass',host:null,rain:true,
 lore:'雪白蛋托里破壳而出，海绵状的柄托举着一顶墨绿黏头，腥臭引得蝇虫聚拢。幼时的"鬼笔蛋"倒是南方人爱吃的一味珍馐。',
 art:{shape:'stinkhorn',h:32,w:14,cap:'#4a3c28',cap2:'#6a5a3a',stemC:'#f2ecd8',sw:.24,volva:true}},
{id:'scleroderma',n:'硬皮马勃',en:'Scleroderma citrinum',biome:'meadow',seasons:[2],r:1,edi:'poison',sub:'grass',host:null,rain:false,
 lore:'草地上滚着一颗颗土黄色的硬球，皮厚如革，切开却是紫黑色的实心——这可不是能吃的马勃，误食者常常追悔莫及。',
 art:{shape:'ball',h:20,w:22,cap:'#c9a850',cap2:'#e0c070',warts:true}},
{id:'geastrum',n:'地星',en:'Geastrum triplex',biome:'meadow',seasons:[2],r:2,edi:'inedible',sub:'grass',host:null,rain:false,
 lore:'干燥的表皮层层开裂外翻，托起中央一颗小小的孢子球，宛如坠地的星辰。秋雨渐歇时，草甸上便冒出一片"星群"。',
 art:{shape:'earthstar',h:22,w:26,cap:'#8a6a48',cap2:'#a8845e',gill:'#c2bba8'}},
{id:'fairyring',n:'硬柄小皮伞',en:'Marasmius oreades',biome:'meadow',seasons:[1,2],r:0,edi:'edible',sub:'ring',host:null,rain:true,
 lore:'细柄坚韧如皮筋，风干了泡水还能复活。爱绕着圈子生长，一夜之间在草地上画出一圈仙女踏过的痕迹。',
 art:{shape:'convex',h:16,w:14,cap:'#b8875a',cap2:'#d0a476',gill:'#e8d4b0',stemC:'#c9a878',sw:.14}},
{id:'mongolicum',n:'蒙古口蘑',en:'Tricholoma mongolicum',biome:'meadow',seasons:[2],r:3,edi:'edible',sub:'ring',host:null,rain:false,
 lore:'白胖敦实，专挑草原上羊群踏过的旧圈生长。塞外秋风一起，牧民便知这是攒了一整年的鲜。价比黄金，一年难得几回。',
 art:{shape:'umbo',h:36,w:36,cap:'#f4f0e2',cap2:'#e2d8bc',gill:'#f2ecd8',stemC:'#eee6cc',sw:.3,fib:true,umboC:'#e8dcc0'}},
{id:'sordida',n:'花脸香蘑',en:'Lepista sordida',biome:'meadow',seasons:[2],r:1,edi:'edible',sub:'grass',host:null,rain:false,
 lore:'青灰泛蓝的伞面平展如碟，深秋草地上格外惹眼。近亲紫丁香蘑爱扎堆，它却总喜欢独自站在稍远的一隅。',
 art:{shape:'flat',h:18,w:24,cap:'#7a7cb0',cap2:'#9a9cd0',gill:'#8a86ae',stemC:'#9088b0',sw:.24}},
{id:'agrocybe',n:'田头菇',en:'Agrocybe praecox',biome:'meadow',seasons:[0,1],r:0,edi:'edible',sub:'grass',host:null,rain:true,
 lore:'蜜黄小伞成片钻出田埂草丛，菌柄上留着一圈薄薄的环。春夏之交最是勤快，一场雨后转眼就冒出一茬。',
 art:{shape:'convex',h:22,w:22,cap:'#e0b83a',cap2:'#f0d068',gill:'#c9a860',stemC:'#e8d8a0',sw:.2,ring:true}},
{id:'cristata',n:'冠状环柄菇',en:'Lepiota cristata',biome:'meadow',seasons:[1],r:1,edi:'poison',sub:'grass',host:null,rain:false,
 lore:'惨白的小伞顶着一圈锈红鳞片，像戴了顶褪色的皇冠。个头虽小却暗藏毒性，与近亲高大环柄菇切不可混淆。',
 art:{shape:'umbo',h:16,w:14,cap:'#ece4d0',cap2:'#d8c8a8',gill:'#c9b088',stemC:'#e2d8bc',sw:.16,ring:true,scales:true,scaleC:'#9a3a1e',umboC:'#7a2c14'}},
/* ---------- 松针林 pine ---------- */
{id:'matsu',n:'松茸',en:'Tricholoma matsutake',biome:'pine',seasons:[2],r:4,edi:'edible',sub:'buried',host:'pine',rain:false,
 lore:'秋雨后的松林里，落叶下微微隆起一小块土——那底下是菌中之王。破土时的辛香，值千金。',
 art:{shape:'convex',h:34,w:30,cap:'#b08a55',cap2:'#caa268',gill:'#efe6d0',stemC:'#e6d8b4',sw:.34,fib:true,scales:true,scaleC:'#8a6538'}},
{id:'saffron',n:'松乳菇',en:'Lactarius deliciosus',biome:'pine',seasons:[2],r:1,edi:'edible',sub:'ground',host:'pine',rain:false,
 lore:'橙红的伞面带同心环纹，掰开会渗出胡萝卜色的乳汁，伤口过夜泛出铜绿。江南人叫它雁来蕈。',
 art:{shape:'funnel',h:22,w:28,cap:'#d9893c',cap2:'#c07028',stemC:'#e09a55',sw:.34,zones:true,specks:4,speckC:'#7a8f5a'}},
{id:'russula',n:'正红菇',en:'Russula griseocarnosa',biome:'pine',seasons:[1,2],r:0,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'艳红的圆盖配雪白菌柄，散在松下如点点灯笼。闽地月子汤里的红菇正是它，汤色绯红。',
 art:{shape:'flat',h:24,w:28,cap:'#c9363a',cap2:'#e05a52',gill:'#f2ecdc',stemC:'#f1ece0',sw:.3}},
{id:'suillus',n:'褐环乳牛肝菌',en:'Suillus luteus',biome:'pine',seasons:[2],r:0,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'伞面裹着一层栗色黏液，雨后亮得像上了釉，故洋名"滑杰克"。去皮再吃，肠胃才不闹脾气。',
 art:{shape:'convex',h:24,w:28,cap:'#8a5526',cap2:'#a87038',gill:'#e0cf8a',stemC:'#e2d4a8',sw:.3,slime:true,ring:true}},
{id:'morel',n:'羊肚菌',en:'Morchella esculenta',biome:'pine',seasons:[0],r:3,edi:'edible',sub:'ground',host:null,rain:true,
 lore:'蜂窝状的脑纹伞帽，通体中空如海绵。它是春天的信使——雪一化，火烧迹地与河滩最先冒出它。',
 art:{shape:'morel',h:30,w:22,cap:'#9a7d4a',cap2:'#5f4c2c',stemC:'#e6dcc2',sw:.36}},
{id:'lanmao',n:'见手青',en:'Lanmaoa asiatica',biome:'pine',seasons:[1],r:2,edi:'careful',sub:'ground',host:'pine',rain:true,
 lore:'指尖一碰，伤处倏地泛出靛蓝。云南雨季的传奇，炒不熟会"见小人"，却年年有人为它赴汤蹈火。',
 art:{shape:'convex',h:30,w:32,cap:'#7d4a30',cap2:'#9a6240',gill:'#d8b84a',stemC:'#c9944a',sw:.4,specks:6,speckC:'#3f5f9a'}},
{id:'coral',n:'珊瑚菌',en:'Ramaria',biome:'pine',seasons:[1,2],r:1,edi:'careful',sub:'ground',host:null,rain:false,
 lore:'林地里长出的一丛"珊瑚"，杏黄的枝桠向上开花。滇人唤作扫把菌，水焯之后凉拌最佳。',
 art:{shape:'coral',h:26,w:26,cap:'#d9a84a',cap2:'#f0dca0'}},
{id:'honey',n:'蜜环菌',en:'Armillaria mellea',biome:'pine',seasons:[2],r:0,edi:'edible',sub:'stump',host:null,rain:false,
 lore:'蜜色的小伞成大簇围着树桩，东北人叫它榛蘑——小鸡炖蘑菇里的那一味，正是山里的它。',
 art:{shape:'convex',h:24,w:16,cap:'#b9884a',cap2:'#d0a260',gill:'#e8dcc0',stemC:'#cdb488',sw:.18,ring:true,specks:5,speckC:'#7a5426',cluster:4}},
/* ---------- 松针林 pine 新增（E3 批B） ---------- */
{id:'rivet',n:'血红铆钉菇',en:'Chroogomphus rutilus',biome:'pine',seasons:[2],r:1,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'暗红黏滑的伞盖挨着乳牛肝菌一同破土，故有"铆钉菇"之名——像是钉在松林地上的一枚枚锈钉。菌褶老熟后转为灰紫，肉质紧实但滋味平平。',
 art:{shape:'convex',h:26,w:24,cap:'#7a2a2e',cap2:'#9c4038',gill:'#7a6a78',stemC:'#d9c878',sw:.2,slime:true}},
{id:'virescens',n:'铜绿红菇',en:'Russula virescens',biome:'pine',seasons:[1],r:1,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'青苔般的伞面龟裂成不规则的碎瓷纹，是红菇属里少见的绿色成员。江南人称"绿菇"，看似诡异实则鲜甜，与近亲的红菇同样金贵。',
 art:{shape:'flat',h:22,w:28,cap:'#8fa06a',cap2:'#b8c48a',gill:'#f2eee0',stemC:'#f0ece0',sw:.28,specks:14,speckC:'#5f7048'}},
{id:'oldman',n:'松塔牛肝菌',en:'Strobilomyces strobilaceus',biome:'pine',seasons:[2],r:1,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'灰黑粗鳞层层叠叠，如老人斑白蓬乱的须发，俗名"老人头"。菌孔幼时雪白，触碰即转黑，煮汤鲜香不输正牌牛肝菌。',
 art:{shape:'convex',h:30,w:30,cap:'#3c352c',cap2:'#5c5044',pore:true,poreC:'#8a7d68',stemC:'#6a5c48',sw:.3,scales:true,scaleC:'#231e18'}},
{id:'grevillei',n:'厚环乳牛肝菌',en:'Suillus grevillei',biome:'pine',seasons:[2,3],r:0,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'金黄油亮的伞盖裹着一层厚滑黏液，柄上系着松软的鹅黄菌环，雨后的松林里格外惹眼。深秋至初冬头场霜降前都能寻见，去皮再食，肠胃才安稳。',
 art:{shape:'convex',h:26,w:30,cap:'#e0aa28',cap2:'#f4d068',pore:true,poreC:'#f0dc90',stemC:'#e8d090',sw:.3,slime:true,ring:true}},
{id:'ganba',n:'干巴菌',en:'Thelephora ganbajun',biome:'pine',seasons:[1,2],r:3,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'云南人心尖上的珍馐，形似枯枝败叶，暗褐里夹着松针般的墨绿，混在松毛堆里极难辨认。寻见一窝能欢喜一整个雨季，价比肉贵，晒不得暴晒。',
 art:{shape:'coral',h:22,w:26,cap:'#3a3228',cap2:'#5c6b46'}},
{id:'amethyst',n:'紫晶蜡蘑',en:'Laccaria amethystina',biome:'pine',seasons:[2],r:0,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'通体紫得像浸透了葡萄汁，伞小柄细，成片从松针地里钻出。颜色越晒越淡，山民笑称它是"会褪色的小紫伞"。',
 art:{shape:'convex',h:16,w:14,cap:'#7a4a9c',cap2:'#9868b8',gill:'#8a5cae',stemC:'#8a5cae',sw:.16}},
{id:'hatsudake',n:'红汁乳菇',en:'Lactarius hatsudake',biome:'pine',seasons:[2],r:1,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'掰开伞肉便渗出酒红色乳汁，触之转为墨绿。是松乳菇的近亲兄弟，颜色更深、滋味也更浓烈，同样只肯在松林下现身。',
 art:{shape:'trumpet',h:24,w:26,cap:'#b8422a',cap2:'#8f2e1c',stemC:'#c96040',sw:.3,specks:5,speckC:'#4a6b3a'}},
{id:'saponaceum',n:'皂味口蘑',en:'Tricholoma saponaceum',biome:'pine',seasons:[2],r:1,edi:'careful',sub:'ground',host:'pine',rain:false,
 lore:'灰褐色的伞面朴素无奇，柄基常泛出一点淡淡的粉色，凑近一闻却是浓浓的皂角味，故此得名。滋味平平还需多焯几水，图个安心。',
 art:{shape:'convex',h:26,w:26,cap:'#8a8570',cap2:'#a49f88',gill:'#e6e0cc',stemC:'#d9c2b0',sw:.24,fib:true}},
{id:'deadlyweb',n:'血红丝膜菌',en:'Cortinarius rubellus',biome:'pine',seasons:[2],r:2,edi:'deadly',sub:'ground',host:'pine',rain:false,
 lore:'橙红棕色的伞面裹着一层蛛丝般的菌幕，欧洲人唤它"死亡丝膜"。中毒后要数日才现肾衰之兆，偏又与鲜美的红菇同林而居，最忌贪杯下箸认错人。',
 art:{shape:'convex',h:24,w:22,cap:'#9c3820',cap2:'#bf5a34',gill:'#a8763a',stemC:'#c9a068',sw:.2,fib:true}},
{id:'sparassis',n:'绣球菌',en:'Sparassis crispa',biome:'pine',seasons:[2],r:2,edi:'edible',sub:'trunk',host:'pine',rain:false,
 lore:'米白色的菌瓣层层叠叠如一团绽开的绣球，蜷伏在老松树根旁。质地脆嫩似海蜇，是东北林区秋日里的稀罕货。',
 art:{shape:'brain',h:26,w:34,cap:'#e8e0c4',cap2:'#d0c49c',stemC:'#c9bc94',sw:.3}},
/* ---------- 溪谷湿地 wetland ---------- */
{id:'angel',n:'鳞柄白鹅膏',en:'Amanita virosa',biome:'wetland',seasons:[1,2],r:2,edi:'deadly',sub:'ground',host:'birch',rain:false,
 lore:'通体纯白，亭亭如天使降世。可它是世上最危险的蘑菇之一——"毁灭天使"，半朵即可致命。',
 art:{shape:'convex',h:30,w:26,cap:'#f2efe2',cap2:'#e2dcc8',gill:'#f6f2e6',stemC:'#f2efe2',sw:.24,ring:true,volva:true,fib:true}},
{id:'deathcap',n:'毒鹅膏',en:'Amanita phalloides',biome:'wetland',seasons:[1,2],r:3,edi:'deadly',sub:'ground',host:'oak',rain:false,
 lore:'橄榄绿的伞面带丝光，样貌平平无奇，却是史上夺命最多的一朵菇。它常静静站在栎树荫里。',
 art:{shape:'convex',h:28,w:28,cap:'#9aa066',cap2:'#b8bc88',gill:'#f2eedc',stemC:'#eee9d6',sw:.26,ring:true,volva:true,fib:true}},
{id:'mycena',n:'荧光小菇',en:'Mycena chlorophos',biome:'wetland',seasons:[1],r:3,edi:'inedible',sub:'wood',host:null,rain:true,glow:'#8fffbe',
 lore:'梅雨夜里，倒木上亮起一排幽绿的小灯。白天它只是不起眼的灰白小菇，夜晚才显出真身。',
 art:{shape:'bell',h:18,w:12,cap:'#cfe8d2',cap2:'#a8d8b4',gill:'#e8f4e8',stemC:'#d8ecd8',sw:.14,glow:'#8fffbe',cluster:3,alpha:.95}},
{id:'gyromitra',n:'鹿花菌',en:'Gyromitra esculenta',biome:'wetland',seasons:[0],r:2,edi:'deadly',sub:'ground',host:'pine',rain:false,
 lore:'红褐的伞帽皱褶如脑。北欧人执意煮了又煮拿它当春鲜，但生食剧毒，蒸汽也能伤人。',
 art:{shape:'brain',h:24,w:26,cap:'#8a4530',cap2:'#a8603f',stemC:'#d8c2a8',sw:.4}},
{id:'waxcap',n:'绯红湿伞',en:'Hygrocybe coccinea',biome:'wetland',seasons:[2],r:1,edi:'inedible',sub:'grass',host:null,rain:true,
 lore:'蜡质的绯红锥帽湿润发亮，秋雨后的苔藓地上，像谁撒了一把小火苗。',
 art:{shape:'conical',h:20,w:16,cap:'#e0442a',cap2:'#f06a3a',gill:'#f0b060',stemC:'#f0a040',sw:.2,slime:true}},
{id:'sulphur',n:'硫磺菌',en:'Laetiporus sulphureus',biome:'wetland',seasons:[1,2],r:2,edi:'careful',sub:'trunk',host:'willow',rain:false,
 lore:'橙黄的波浪层层叠在老柳树干上，鲜嫩时口感似鸡，洋名便叫"林中之鸡"。老了则柴如朽木。',
 art:{shape:'shelf',h:28,w:36,cap:'#f0942e',cap2:'#e07a1a',gill:'#f7d060',layers:3,rimC:'#f7c84a'}},
{id:'shaggy',n:'毛头鬼伞',en:'Coprinus comatus',biome:'wetland',seasons:[0,2],r:1,edi:'careful',sub:'ground',host:null,rain:true,
 lore:'白色的长圆筒披满翻卷的鳞毛，俗名鸡腿菇。雨后从溪边小径钻出，几小时内就会自融成墨。',
 art:{shape:'shaggy',h:34,w:16,cap:'#f0ece0',cap2:'#d9d0ba',stemC:'#eee9da',sw:.2,ring:true}},
/* ---------- 溪谷湿地 wetland 新增（E3 批B） ---------- */
{id:'scarletcup',n:'猩红肉盘菌',en:'Sarcoscypha coccinea',biome:'wetland',seasons:[3,0],r:1,edi:'inedible',sub:'wood',host:null,rain:true,
 lore:'寒冬雪后，溪畔枯枝上冒出一只只猩红的小杯，内壁艳红夺目，外壁却裹着雪白绒毛。是冬春交替时林间难得一见的亮色，看看就好，不必采食。',
 art:{shape:'cup',h:14,w:20,cap:'#f0ece0',gill:'#c9182a',stemC:'#e8e2d0',sw:.14}},
{id:'militaris',n:'蛹虫草',en:'Cordyceps militaris',biome:'wetland',seasons:[1,2],r:2,edi:'med',sub:'buried',host:null,rain:true,
 lore:'橙红的棒状子座从埋在土里的蛾蛹上钻出，虫体与真菌合而为一，正是市面上"虫草花"的野生原型。夏秋雨润时循着一点橙色才能寻见。',
 art:{shape:'club',h:26,w:10,cap:'#d9451e',stemC:'#e8a04a',headFrac:.34,scab:true}},
{id:'helvella',n:'皱柄白马鞍菌',en:'Helvella crispa',biome:'wetland',seasons:[2],r:1,edi:'careful',sub:'ground',host:null,rain:true,
 lore:'灰白的伞盖褶皱如揉皱的马鞍，菌柄带纵向浅沟宛如肋骨。羊肚菌的远房表亲，气味清淡，务必久煮透熟，生食伤肠胃。',
 art:{shape:'morel',h:26,w:16,cap:'#e2dcc4',cap2:'#c9c0a0',stemC:'#f0ece0',sw:.3}},
{id:'sinuatum',n:'毒粉褶菌',en:'Entoloma sinuatum',biome:'wetland',seasons:[1],r:1,edi:'poison',sub:'ground',host:'oak',rain:true,
 lore:'灰褐色的伞盖敦实肥厚，貌似可口的口蘑，菌褶却渐渐转为粉红——这正是它剧烈肠胃毒性的信号，欧洲误食中毒事件里常有它的身影。',
 art:{shape:'convex',h:26,w:28,cap:'#8a7d68',cap2:'#a8987c',gill:'#d88a9c',stemC:'#e6ddc8',sw:.26}},
{id:'panellus',n:'亚侧耳',en:'Panellus serotinus',biome:'wetland',seasons:[3],r:0,edi:'edible',sub:'wood',host:null,rain:false,
 lore:'青灰泛橄榄绿的小扇贴在寒木上，是雪落时节难得还在生长的野味。日本人称它"占地茸"，油炸格外香脆。',
 art:{shape:'shelf',h:18,w:24,cap:'#5f7d78',cap2:'#7a9c8a',gill:'#e0d8a0',layers:1}},
{id:'cortvarius',n:'黄丝膜菌',en:'Cortinarius varius',biome:'wetland',seasons:[2],r:0,edi:'inedible',sub:'ground',host:'birch',rain:true,
 lore:'明黄褐色的伞盖裹着一层细密丝膜，桦树下成片探头。滋味不明也无人细究，山民多绕道而行，只作个观赏的念想。',
 art:{shape:'convex',h:24,w:24,cap:'#a8883c',cap2:'#c9a860',gill:'#a8843a',stemC:'#e6d8a8',sw:.24,fib:true}},
{id:'semisang',n:'半血红丝膜菌',en:'Cortinarius semisanguineus',biome:'wetland',seasons:[2],r:1,edi:'poison',sub:'ground',host:'birch',rain:true,
 lore:'土黄褐色的伞面下藏着一圈触目惊心的血红菌褶，故名"半血红"。含有微毒，与血红丝膜菌同科同源，见者不妨敬而远之。',
 art:{shape:'convex',h:22,w:22,cap:'#9c5a34',cap2:'#b8763e',gill:'#8a1420',stemC:'#c9a878',sw:.22,fib:true}},
/* ---------- 竹林幽径 bamboo（E3 批C，新环境首批物种） ---------- */
{id:'longskirt',n:'长裙竹荪',en:'Dictyophora indusiata',biome:'bamboo',seasons:[1],r:3,edi:'edible',sub:'ground',host:'bamboo',rain:true,
 lore:'竹林雨后，网裙从蛋托里缓缓撑开，如仙子曳地长裙，故称"菌中皇后"。清晨采得最是鲜嫩，裙网越密越珍贵，是竹乡人家待客的体面菜。',
 art:{shape:'veiled',h:34,w:14,cap:'#3a3226',cap2:'#5a4c3a',stemC:'#f4f0e0',sw:.22,volva:true,net:9}},
{id:'shortskirt',n:'短裙竹荪',en:'Dictyophora duplicata',biome:'bamboo',seasons:[1],r:1,edi:'edible',sub:'ground',host:'bamboo',rain:true,
 lore:'与长裙竹荪同科，裙摆却只探出一小截便戛然而止，网眼也稀疏得多。滋味不及"皇后"精细，寻常人家倒也吃得香甜。',
 art:{shape:'veiled',h:26,w:12,cap:'#8a5040',cap2:'#a86850',stemC:'#f0ece0',sw:.2,volva:true,net:4}},
{id:'shiraia',n:'竹黄',en:'Shiraia bambusicola',biome:'bamboo',seasons:[1,2],r:1,edi:'med',sub:'trunk',host:'bamboo',rain:false,
 lore:'寄生在活竹竿上的粉红瘤块，表皮粗粝如痂，剖开却渗出暗红汁液。江南药农专寻它入药，治跌打损伤颇有奇效。',
 art:{shape:'ball',h:20,w:22,cap:'#c96a72',cap2:'#e0949a',warts:true}},
{id:'bambooegg',n:'竹荪蛋',en:'Dictyophora indusiata (egg)',biome:'bamboo',seasons:[1],r:1,edi:'careful',sub:'ground',host:'bamboo',rain:true,
 lore:'竹荪破壳前的模样，浑圆如鹅卵，裹着一层胶质白膜。老饕爱取来炖汤，只是模样酷似毒鹅膏的幼期菌蛋，采时务必认清竹林方位、莫贪野地里来路不明的"蛋"。',
 art:{shape:'ball',h:20,w:20,cap:'#f0ece0',cap2:'#e0d8c4',slime:true}},
{id:'macrocybe',n:'大杯伞',en:'Macrocybe gigantea',biome:'bamboo',seasons:[1,2],r:1,edi:'edible',sub:'ground',host:null,rain:true,
 lore:'竹叶腐土上撑起的巨伞，伞面能大过斗笠，柄粗如小儿手臂。南方菇农论堆采收，切片晒干煮汤格外鲜甜。',
 art:{shape:'funnel',h:34,w:38,cap:'#e8e0c8',cap2:'#d0c4a0',stemC:'#e4dcc0',sw:.34}},
{id:'bamboolittle',n:'竹林小皮伞',en:'Marasmius sp.',biome:'bamboo',seasons:[1,2],r:0,edi:'inedible',sub:'ground',host:null,rain:true,
 lore:'竹叶堆里冒出的针尖小伞，一夜生千朵，太阳一晒又尽数枯萎。个头太小无人采食，倒是林间最热闹的点缀。',
 art:{shape:'convex',h:11,w:9,cap:'#e0b458',cap2:'#f2d888',gill:'#fbf0cc',stemC:'#e8d8a8',sw:.12,cluster:5}},
{id:'grasstermit',n:'草鸡枞',en:'Termitomyces microcarpus',biome:'bamboo',seasons:[1,2],r:2,edi:'edible',sub:'ground',host:null,rain:true,
 lore:'鸡枞属里最玲珑的一种，个头不及拇指，却也与白蚁巢脉脉相连。竹林雨后成片钻出草丛，伞尖一点乌褐，鲜味不输它高大的近亲。',
 art:{shape:'umbo',h:20,w:13,cap:'#8a7c68',cap2:'#a89880',gill:'#e8ddc4',stemC:'#d8cba8',sw:.16,umboC:'#3c3226',cluster:2}},
{id:'blackblood',n:'亚稀褐红菇',en:'Russula subnigricans',biome:'bamboo',seasons:[1],r:2,edi:'deadly',sub:'ground',host:'bamboo',rain:true,
 lore:'灰褐色的伞盖伤后转黑不变红，是红菇属里最凶险的一员。误食者数小时内便见横纹肌溶解之祸——切记，伤面会转红的红菇才安全，转黑的万万不可下箸。',
 art:{shape:'flat',h:24,w:28,cap:'#5c4038',cap2:'#7a5850',gill:'#c9a89c',stemC:'#d8c2b8',sw:.28,specks:6,speckC:'#2a1c18'}},
{id:'ophiobarnesii',n:'亚香棒虫草',en:'Ophiocordyceps barnesii',biome:'bamboo',seasons:[0],r:2,edi:'med',sub:'buried',host:null,rain:false,
 lore:'蛰伏地下的虫蛾早被真菌噬空躯壳，唯留一根香褐色的子座破土而出。滇南药农拿它替代冬虫夏草，价廉却也温补。',
 art:{shape:'club',h:24,w:9,cap:'#3a2f22',stemC:'#c9a468',headFrac:.22,scab:true}},
{id:'disseminatus',n:'丛枝鬼伞',en:'Coprinellus disseminatus',biome:'bamboo',seasons:[0,2,3],r:0,edi:'inedible',sub:'stump',host:null,rain:true,
 lore:'老竹桩四周挤出上百朵米粒大小的灰伞，密密麻麻如蚁群列队，故又唤"仙女帽"。不化墨也不宜食，看个热闹便好。',
 art:{shape:'bell',h:12,w:8,cap:'#b8ac96',cap2:'#d0c4a8',gill:'#8a7c68',stemC:'#e6ddc8',sw:.16,cluster:5,fib:true}},
{id:'bamboonest',n:'竹林鸟巢菌',en:'Cyathus striatus',biome:'bamboo',seasons:[1,2],r:1,edi:'inedible',sub:'ground',host:null,rain:true,
 lore:'竹叶腐殖层里立着一只只灰褐小酒盅，盅底卧着几粒扁圆"鸟卵"，雨点砸落便将卵粒弹射老远，靠这法子撒播孢子。',
 art:{shape:'nest',h:12,w:14,cap:'#8a7050',cap2:'#a89068',gill:'#e8dcc0',eggs:4}},
{id:'marasmiellus',n:'皮微皮伞',en:'Marasmiellus candidus',biome:'bamboo',seasons:[2,3],r:0,edi:'inedible',sub:'ground',host:null,rain:false,
 lore:'竹叶脉络间趴着几点近乎透明的白伞，薄得能透光，风一吹便瑟瑟发抖。个头太小太脆，采下来一捏就化。',
 art:{shape:'bell',h:9,w:8,cap:'#f0ece0',cap2:'#e0d8c8',gill:'#e8e0d0',stemC:'#e8e0d0',sw:.16,alpha:.88}},
/* ---------- 灵境秘林 grove ---------- */
{id:'azure',n:'蓝灵菇',en:'Azure Spirit Cap',biome:'grove',seasons:[0,1,2,3],r:4,edi:'inedible',sub:'ground',host:null,rain:false,glow:'#4ad2ff',
 lore:'灵境深处的蓝焰。凝望久了，仿佛能听见风在菌褶间的低语。',
 art:{shape:'convex',h:26,w:26,cap:'#3fb8e8',cap2:'#7adcff',gill:'#c8f0ff',stemC:'#a8e6ff',sw:.22,warts:6,wartC:'#d6f7ff',glow:'#4ad2ff'}},
{id:'starlight',n:'星辉菇',en:'Starlight Shroom',biome:'grove',seasons:[0,1,2,3],r:4,edi:'inedible',sub:'ground',host:null,rain:false,glow:'#ffe9a0',
 lore:'深蓝的伞面缀满星屑。据说是坠落的星辰在林间生了根，夜里为迷路的旅人引路。',
 art:{shape:'bell',h:28,w:22,cap:'#2e3370',cap2:'#4a4f9a',gill:'#8a8fd0',stemC:'#9fa6e6',sw:.2,specks:9,speckC:'#ffe9a0',glow:'#fff0a0'}},
{id:'rainbow',n:'虹伞菌',en:'Rainbow Parasol',biome:'grove',seasons:[0,1,2,3],r:4,edi:'inedible',sub:'grass',host:null,rain:false,
 lore:'七彩的华盖撑在长柄上。传说采到它的人，会被好运缠绕一整年。',
 art:{shape:'umbo',h:38,w:34,cap:'#e85a8a',cap2:'#f08aa8',gill:'#f0e0e8',stemC:'#e8d8c0',sw:.15,ring:true,rainbow:true}},
{id:'ember',n:'心火菇',en:'Emberheart',biome:'grove',seasons:[1],r:3,edi:'inedible',sub:'ground',host:null,rain:false,glow:'#ff7a3c',
 lore:'锥顶内里像揣着一团不灭的炭火，落雪也焐不凉。触手温热，如握着一颗小小的心。',
 art:{shape:'conical',h:26,w:20,cap:'#ff7a3c',cap2:'#ffb060',gill:'#ffd090',stemC:'#d65a2a',sw:.22,glow:'#ff7a3c',slime:true}},
{id:'mist',n:'雾灵菇',en:'Mistwraith',biome:'grove',seasons:[2],r:3,edi:'inedible',sub:'ground',host:null,rain:false,glow:'#cfe8ff',
 lore:'半透明如凝成形状的薄雾。伸手去摘时，常常扑了个空——它又在三步之外静静立着。',
 art:{shape:'bell',h:26,w:22,cap:'#bcd6ee',cap2:'#dcecf8',gill:'#e8f2fa',stemC:'#d6e6f4',sw:.2,glow:'#cfe8ff',alpha:.82}},
{id:'eldra',n:'古龙芝',en:'Elderdragon Bracket',biome:'grove',seasons:[0,1,2,3],r:4,edi:'med',sub:'trunk',host:null,rain:false,
 lore:'翠玉镶金的巨大层菌，盘踞古树千年。指尖抚过环纹，能感到一下极缓的、大地般的心跳。',
 art:{shape:'shelf',h:30,w:40,cap:'#2f7d5b',cap2:'#4aa078',gill:'#d9e8c8',layers:2,zones:true,rimC:'#d9b84a',slime:true}},
/* ---------- 灵境秘林 grove 新增（E3 批C） ---------- */
{id:'moonveil',n:'月华伞',en:'Moonveil Cap',biome:'grove',seasons:[0,1,2,3],r:4,edi:'inedible',sub:'grass',host:null,rain:false,glow:'#eaf2ff',
 lore:'满月夜里才显真容的银白伞盖，伞顶一点莹白似凝住的月光。旅人说，摘下它的刹那，云隙会漏下一线真正的月辉。',
 art:{shape:'umbo',h:28,w:28,cap:'#9aa4c2',cap2:'#c2ccdd',gill:'#e8ecf7',stemC:'#dfe4f5',sw:.22,specks:9,speckC:'#f5f8ff',umboC:'#f5f8ff',glow:'#eaf2ff'}},
{id:'starcore',n:'星髓菇',en:'Starcore Stalk',biome:'grove',seasons:[3],r:3,edi:'inedible',sub:'ground',host:null,rain:false,glow:'#9a7ae0',
 lore:'深冬的灵境里立起一根幽紫的菌柱，顶端的孢囊像凝固的星屑，彻夜低吟着听不懂的光之语言。',
 art:{shape:'club',h:26,w:11,cap:'#9a7ae0',stemC:'#3a2b52',headFrac:.36,scab:true,glow:'#9a7ae0'}},
{id:'veilmist',n:'幻雾冠',en:'Veilmist Crown',biome:'grove',seasons:[0],r:4,edi:'inedible',sub:'ground',host:null,rain:false,glow:'#9af0c6',
 lore:'春雾漫过灵境时才现身的半透明冠伞，网裙比竹林里的竹荪更加轻盈，指尖一碰便如烟一般散作雾气。',
 art:{shape:'veiled',h:30,w:13,cap:'#8fd8b0',stemC:'#eafaf0',sw:.2,net:8,alpha:.72,glow:'#9af0c6'}},
{id:'candlecap',n:'灵烛菌',en:'Candlecap Wisp',biome:'grove',seasons:[0,1,2,3],r:3,edi:'med',sub:'stump',host:null,rain:false,glow:'#ffd76a',
 lore:'老树桩上立着一豆不灭的烛火，伞面淌着蜡油般的黏光，暖意能焐热雪夜里冻僵的手。灵药铺子最爱收它入方。',
 art:{shape:'convex',h:24,w:18,cap:'#ffd76a',cap2:'#ffe8a0',gill:'#f0c860',stemC:'#e8c060',sw:.2,slime:true,glow:'#ffd76a'}},
{id:'dreamjelly',n:'梦缘胶菇',en:'Dreambound Jelly',biome:'grove',seasons:[2,3],r:4,edi:'inedible',sub:'trunk',host:null,rain:false,glow:'#d76adf',
 lore:'古树伤疤处凝出一团紫粉色的胶质，触之微凉，据说枕着它入睡，能梦见从未去过的地方。',
 art:{shape:'jelly',h:22,w:26,cap:'#d76adf',cap2:'#f0a8ff',alpha:.85,glow:'#d76adf'}},
/* ---------- 高山苔甸 alpine（E3 批C，新环境首批物种） ---------- */
{id:'sinensis',n:'冬虫夏草',en:'Ophiocordyceps sinensis',biome:'alpine',seasons:[0],r:4,edi:'med',sub:'buried',host:null,rain:false,
 lore:'高原积雪初融，虫尸与真菌合而为一，头顶一根乌褐色的子座破土而立。挖掘者伏在草甸上寸寸摸索，一根虫草，一份生计。',
 art:{shape:'club',h:24,w:10,cap:'#2a2018',stemC:'#c9a860',headFrac:.3,scab:true}},
{id:'alpinemorel',n:'高山羊肚菌',en:'Morchella tridentina',biome:'alpine',seasons:[0],r:2,edi:'edible',sub:'ground',host:null,rain:true,
 lore:'雪线之下最先苏醒的菌子，蜂窝状的黑褐伞帽比林间的羊肚菌更瘦更深色，融雪水一漫过草甸便钻出地面。',
 art:{shape:'morel',h:26,w:18,cap:'#3c3226',cap2:'#5a4c38',stemC:'#e8e0cc',sw:.34}},
{id:'snowrussula',n:'雪山红菇',en:'Russula alpina',biome:'alpine',seasons:[1],r:1,edi:'edible',sub:'ground',host:'pine',rain:true,
 lore:'矮曲松脚下的一点艳色，粉红伞面比山下的红菇更浅更冷，短暂的高山夏天里，它是苔草间唯一鲜亮的旗帜。',
 art:{shape:'flat',h:20,w:24,cap:'#d9587a',cap2:'#f0829e',gill:'#f6eee6',stemC:'#f2ece0',sw:.3}},
{id:'alpinetricholoma',n:'高山口蘑',en:'Tricholoma alpinum',biome:'alpine',seasons:[2],r:1,edi:'edible',sub:'ground',host:'pine',rain:false,
 lore:'秋霜落定后的苔草地上，一顶顶敦厚的白伞挨着矮松探出头，牧民采来炖汤，说是能压得住山风的寒气。',
 art:{shape:'convex',h:26,w:26,cap:'#e8e4d4',cap2:'#d4cdb2',gill:'#f0ecd8',stemC:'#e4dcc4',sw:.28,fib:true}},
{id:'earthspoon',n:'地匙菌',en:'Spathularia flavida',biome:'alpine',seasons:[2],r:0,edi:'inedible',sub:'ground',host:null,rain:false,
 lore:'苔藓间立着一柄柄浅黄的小勺子，扁平宽大的头微微卷曲，像谁遗落在山间的餐具。不苦不毒，却也无人问津。',
 art:{shape:'club',h:13,w:19,cap:'#c2b158',stemC:'#e8dcac',headFrac:.72}},
{id:'caloscypha',n:'橙黄网孢盘菌',en:'Caloscypha fulgens',biome:'alpine',seasons:[0],r:0,edi:'inedible',sub:'ground',host:'pine',rain:false,
 lore:'残雪边缘的矮松针下，一只只橙黄小碗贴地而生，内壁鲜亮如烈焰，外壁却常带一圈青蓝色的锈斑。',
 art:{shape:'cup',h:12,w:16,cap:'#e8a030',gill:'#ff8a1a',stemC:'#e0982c'}},
{id:'alpinecoral',n:'高山珊瑚菌',en:'Clavaria alpina',biome:'alpine',seasons:[1],r:1,edi:'careful',sub:'ground',host:null,rain:true,
 lore:'苔草丛里立着一丛雪白的珊瑚，枝桠纤细易折，比松林里的杏黄珊瑚菌更显清冷孤傲。焯水后口感爽脆，需防与其他杂色珊瑚菌混淆。',
 art:{shape:'coral',h:20,w:20,cap:'#e8e4d4',cap2:'#f4f0e4'}},
{id:'cudonia',n:'苔地锤舌菌',en:'Cudonia confusa',biome:'alpine',seasons:[2],r:0,edi:'inedible',sub:'ground',host:null,rain:false,
 lore:'锤子般的小小头颅顶在细长柄上，通体鲜黄，混在苔藓与松针间极难察觉，秋日踏勘苔甸时才偶有所见。',
 art:{shape:'club',h:24,w:6,cap:'#e8d020',stemC:'#d8c060',headFrac:.18}},
{id:'snowcup',n:'雪地盘菌',en:'Peziza nivalis',biome:'alpine',seasons:[3,0],r:0,edi:'inedible',sub:'ground',host:null,rain:false,
 lore:'残雪将化未化之际，雪缘冒出一圈灰白色的小盘子，是苔甸上少见的耐寒菌子，专挑最冷的时节露面。',
 art:{shape:'cup',h:12,w:16,cap:'#d4d8dc',gill:'#a8b4bc',stemC:'#c8ccd0'}},
{id:'alpinescleroderma',n:'高山硬皮马勃',en:'Scleroderma polyrhizum',biome:'alpine',seasons:[2],r:1,edi:'poison',sub:'ground',host:null,rain:false,
 lore:'碎石地上鼓起一颗颗灰白硬球，皮比草甸上的近亲更厚更糙，成熟后顶部裂成星芒状开口，孢子借风扬向山谷。切莫当作马勃采食。',
 art:{shape:'ball',h:22,w:24,cap:'#a8a496',cap2:'#c2beac',warts:true}},
];
const SPMAP={};SP.forEach(s=>SPMAP[s.id]=s);
const TOTAL=SP.length;

/* ====================== P2 拟态 / 鉴别 ====================== */
/* 安全种 -> 危险拟态。拟态个体生成时外观完全沿用安全种精灵渲染，真实身份存于 m.trueId */
const MIMICS={button:'angel',straw:'deathcap',morel:'gyromitra'};
/* 六个相关物种的手写鉴别特征（菌褶颜色 / 菌环菌托 / 气味） */
const INSPECT_TRAITS={
  button:   {gill:'菌褶粉褐色，随成熟逐渐加深',   ring:'菌柄基部无菌托，仅有细微菌环痕迹',           smell:'气味温和，带松软菇香'},
  angel:    {gill:'菌褶纯白色，成熟后依旧洁白',   ring:'菌柄基部裹着明显的白色膜质菌托，柄上部有菌环', smell:'气味清淡略甜，不甚刺鼻'},
  straw:    {gill:'菌褶粉褐色，成熟后转为深褐',   ring:'菌柄基部包裹灰褐色苞状菌托，柄上无菌环',       smell:'带谷物般的清甜香气'},
  deathcap: {gill:'菌褶纯白色，从不随成熟转色',   ring:'菌柄基部有肥厚的白色菌托，柄上部另有菌环',     smell:'初闻微甜，放久竟转腐臭'},
  morel:    {gill:'无菌褶，伞面呈规则蜂窝状凹坑', ring:'菌柄中空、表面光滑，基部无菌托',               smell:'清新的坚果与泥土香气'},
  gyromitra:{gill:'无菌褶，伞面呈不规则脑状皱褶', ring:'菌柄内部呈棉絮状，基部同样无菌托',             smell:'带轻微酸涩刺激气味，久闻微呛'},
};
/* 拟态个体与安全种相异、需要标红警示对照的特征字段（每对 1-2 条） */
const MIMIC_WARN_FIELDS={angel:['gill','ring'],deathcap:['gill','smell'],gyromitra:['gill','smell']};
/* 图鉴详情页互链提示文案 */
const MIMIC_TIPS={
  button:'留意菌褶颜色——纯白菌褶加基部菌托，是危险的信号。',
  angel:'留意菌褶颜色——纯白菌褶加基部菌托，是危险的信号。',
  straw:'留意基部菌托——草菇菌托薄软无环，毒鹅膏菌托肥厚且柄上另有菌环。',
  deathcap:'留意基部菌托——草菇菌托薄软无环，毒鹅膏菌托肥厚且柄上另有菌环。',
  morel:'留意伞面纹理——羊肚菌是规则蜂窝状凹坑，鹿花菌是不规则脑状皱褶。',
  gyromitra:'留意伞面纹理——羊肚菌是规则蜂窝状凹坑，鹿花菌是不规则脑状皱褶。',
};
/* ====================== P4 新鲜度 + 一天一局 ====================== */
/* 每过 1 天的新鲜度衰减速率：默认 default；速朽（鬼伞类）0.75；耐存（松露/灵芝/木耳/金针菇）0.10 */
const DECAY={default:.25,inky:.75,shaggy:.75,truffle:.10,reishi:.10,woodear:.10,enoki:.10};
/* 天气图标 / 中文名（HUD、小屋预报、入暮提示共用） */
const WEATHER_ICON={clear:'☀️',cloud:'⛅',rain:'🌧️',fog:'🌫️',snow:'🌨️',leaf:'🍂',firefly:'✨'};
const WEATHER_NAME={clear:'晴',cloud:'多云',rain:'有雨',fog:'起雾',snow:'落雪',leaf:'落叶纷飞',firefly:'流萤'};

/* ====================== P6 品质 / 变异 / 拍照 ====================== */
/* 品质：刷菇时投骰，普通 70% / 肥美 25%（价×1.5，精灵×1.15）/ 极品 5%（价×2.5，精灵×1.3 + 常驻微金闪粒）。
   概率写在此表，world.js 的 addM() 据此掷骰；c=UI 文案着色（普通不着色）。 */
const QUALITY={
  1:{n:'普通',mul:1,c:null},
  2:{n:'肥美',mul:1.5,c:'#d9852a'},
  3:{n:'极品',mul:2.5,c:'#d9a02a'},
};
const QUALITY_P=[.70,.25,.05]; // 普通/肥美/极品 概率（依次累加判定）
/* 变异：独立第二投，与品质互不影响。mul 为售价额外倍率；c 为 UI 着色；美术变换见 utils.js variantColor()。 */
const VARIANTS={
  albino:{n:'白化',ic:'◇',mul:5,p:.015,c:'#8fd8cf'},
  gilded:{n:'鎏金',ic:'◆',mul:5,p:.008,c:'#d9a02a'},
};

/* 非以上六种物种的通用观察文案，由 art / edi 粗略推导 */
function genericTraits(sp){
  const a=sp.art;
  const gill=a.gill?'菌褶细密，颜色因品种而异':
    (a.shape==='puff'||a.shape==='truffle')?'内部近乎实心，无明显菌褶':
    (a.shape==='shelf')?'背面呈细密孔口状，无菌褶':'菌褶结构不甚明显';
  const ring=a.ring?'菌柄上部可见菌环':a.volva?'菌柄基部有菌托包裹':'菌柄光滑，无环无托';
  const smell=(sp.edi==='deadly'||sp.edi==='poison')?'气味平淡甚至略带异味，不可掉以轻心':
    sp.edi==='med'?'气味清苦，带草药气息':'气味自然，带泥土与菌菇的清香';
  return {gill,ring,smell};
}
